### ISSUE TITLE
False positives on `await-async-query` and `no-await-sync-query`

### ISSUE THREAD

**Issue by Belco90** [testing-library/eslint-plugin-testing-library#122]
Related to #120, #114

Since we are checking testing library queries when calling queries member expressions for `await-async-query` and `no-await-sync-query`, we are getting some false positives in some cases:

- when using queries in cypress files
- when using methods with the same name in other places (e.g. `findByTestId` in enzyme tests in a codebase mixing both enzyme and testing library)

The main issue here is that we are checking the queries methods in every single file no matter where the method is coming from, but we should only check those imported from testing library or returned by something imported from testing library. However, I think a first approach could be at least check if testing library is imported in the file to check the methods or not.

**Comment by afontcu** [comment]
Hi! Looks like #137 was merged but this issue is still valid, right? (Just to double check 😇)

**Comment by Belco90** [comment]
Yes, it was only fixed for `no-await-sync-query` but I'm afraid the issue is still there for `await-async-query`.

**Comment by kentcdodds** [comment]
I'm seeing this as well. Also `prefer-screen-queries` is firing on `cy.findByRole`... etc.

**Comment by Belco90** [comment]
Yes, still pending to fix `await-async-query`.

About `prefer-screen-queries` one, that's new I think. There is [this workaround](https://github.com/testing-library/eslint-plugin-testing-library/issues/120#issuecomment-622345740) for another cypress related issue that might work in the meantime.

I hope I can find some time soon to fix those, specially the `await-async-query` one which is one of the first rules so it needs to be updated properly.

**Comment by thomlom** [comment]
As of today, there are two rules that have similar implementations:

- [await-async-query](https://github.com/testing-library/eslint-plugin-testing-library/blob/master/docs/rules/await-async-query.md)
- [await-async-utils](https://github.com/testing-library/eslint-plugin-testing-library/blob/master/docs/rules/await-async-utils.md)

#137 seems to have fixed `await-async-utils` but didn't include the fix for `await-async-query`. I see two solutions to this: 

1. We merge the rules `await-async-utils` and `await-async-query` since they both check the usage of `await` for imported methods. This would result in a breaking change though.
2. We create a util/function that allows to check if an async imported method (whatever the name) has been used throughout the code. Then we make use of that util in these two rules.

WDYT?

**Comment by Belco90** [comment]
1. We could achieve that in next v4 as is still pending.
2. We have now a module for common functionality named `node-utils.ts`. We can move there that shared code.

I'd prefer go for 2 to leave those 2 rules separated for now.

**Comment by thomlom** [comment]
Option 2 sounds good to me. I'll work on it in the next few days 👍
