### ISSUE TITLE
Update documentation to reflect setup when using the CRA version

### ISSUE THREAD

**Issue by gndelia** [testing-library/eslint-plugin-testing-library#242]
Now that this plugin is part of CRA after this PR https://github.com/facebook/create-react-app/pull/8963 we might want to add a mention to it in the docs. Currently, the docs state how to use this plugin standalone, but probably CRA is far popular to ignore it 😛 . Perhaps we could consider

- If I was already using the plugin, what should I do to use the version that comes from CRA? 
- If I want to use it as part of CRA, what should I do? Perhaps it's just highlighting which steps could be skipped, or linking to the CRA docs where the steps are mentioned if any.

**Comment by Belco90** [comment]
Yeah, I have been thinking about it. I even checked other ESLint plugins already included in CRA and they don't mention anything, so not sure what to do.

I guess at least we can add a section within "Installation" to clarify which major version is included in CRA and since when.

**Comment by gndelia** [comment]
yeah something simple should be enough, we don't have to go _that_ fancy 😄

**Comment by Belco90** [comment]
I think we should add this now since CRA uses v4 and we have released v4.

I figured out how to upgrade the plugin to v4 in a CRA project using yarn (with [selective dependency resolution](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/)), but I don't have any idea how to do this with npm.

Additionally, it would be nice to create a PR to upgrade the plugin in CRA. I think @MichaelDeBoey wanted to give it a try.

**Comment by MichaelDeBoey** [comment]
Created a PR to add `eslint-plugin-testing-library@^4.x` to CRA: https://github.com/facebook/create-react-app/pull/10817

**Comment by Belco90** [comment]
Any ideas about how to suggest updating the plugin to v4 in a CRA project using v3 when dependencies are managed with npm? The only thing I can think of is disabling CRA internal ESLint and reinstall ESLint + plugins directly in the project so the user has full control of it, but I would like to avoid this way.
