### ISSUE TITLE
[no-await-sync-events] invalid exception

### ISSUE THREAD

**Issue by ljosberinn** [testing-library/eslint-plugin-testing-library#250]
It's mentioned [here](https://github.com/testing-library/eslint-plugin-testing-library/blob/master/lib/rules/no-await-sync-events.ts#L27):
```js
    // userEvent.type() is an exception, which returns a
    // Promise. But it is only necessary to wait when delay
    // option is specified. So this rule has a special exception
    // for the case await userEvent.type(element, 'abc', {delay: 1234})
```
but `userEvent.type` is [`async` in any case](https://github.com/testing-library/user-event/blob/master/src/type.js#L62) so it always must be awaited:

![image](https://user-images.githubusercontent.com/29307652/98015052-ac9f0980-1dfc-11eb-8848-6203f3a3e5a2.png)

**Comment by Belco90** [comment]
Hi there! We implemented this exception based on [`testing-library/user-event` docs for `type` method](https://github.com/testing-library/user-event#typeelement-text-options):

> To be clear, userEvent.type always returns a promise, but you only need to await the promise it returns if you're using the delay option. Otherwise everything runs synchronously and you can ignore the promise.

I think we can improve the rule docs to clarify this exception, including the proper reference to testing-library/user-event` docs.

**Comment by gndelia** [comment]
`userEvent.type` always returns a promise, but unless using `delay` option, it is always resolved. I guess they did so to be consistent with the response and always return a `Promise` so it wasn't confusing in js in which some scenarios would return a promise, and some others wouldn't.

In TS that wouldn't be a problem because you could type when (And when not) return a Promise for example. But given the promise is not required to be awaited if not using the `delay option`, that's the reason for the existence of this rule. We could clarify it, I agree. I think the idea was to follow the practice of ignoring the promise as the user-event's docs suggest

**Comment by ljosberinn** [comment]
Guess I got kinda led astray here that we don't actually care about the return value of `userEvent.type` since we only await it, only then the returned although fulfilled promise would actually matter since it's simply different.

Technically, `userEvent.type` shouldn't always be async, but conditionally return a promise, leading to `Promise<void> | void`.

**Comment by gndelia** [comment]
yeah I agree. My guess would be that they did it that way to be consistent and not having js users guessing when it is a promise and when it isn't, but I don't know. I also opened today a ticket about improving this in userEvent from the typings POV https://github.com/testing-library/user-event/issues/480

**Comment by ljosberinn** [comment]
Closing this in favor of the mentioned issue then :)
